#!/usr/bin/env bash
# generate-dropins.sh — Generate systemd drop-in files for service status notifications.
#
# Scans server's/system/ for known service units and generates drop-in
# notify.conf files that hook into ExecStartPost/ExecStopPost to send
# webhook notifications on service state changes.
#
# Usage:
#   bash deploy/generate-dropins.sh            # dry-run (default)
#   bash deploy/generate-dropins.sh --apply    # write files + print install cmds
#
# Environment:
#   SYSTEMD_DIR — Override scan directory (default: <repo>/server's/system)
#   OUTPUT_DIR  — Override output dir    (default: <repo>/generated-dropins)

set -uo pipefail

DRY_RUN=true
if [ "${1:-}" = "--apply" ]; then
    DRY_RUN=false
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SYSTEMD_DIR="${SYSTEMD_DIR:-$REPO_ROOT/server's/system}"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/generated-dropins}"

# ──────────────────────────────────────────────────────────────────────────────
# Exact unit → canonical service name mapping.
# Only these units will get drop-ins. Tokpoint-docker is handled by dockerwatch.
# ──────────────────────────────────────────────────────────────────────────────
declare -A UNIT_MAP=(
    ["alfaconnect-bot.service"]="AlfaConnect"
    ["alfaconnect-webapp.service"]="AlfaConnect"
    ["mehmonxona.service"]="Mehmonxona"
    ["odimrepo-backend.service"]="Odimrepo"
    ["odimrepo-frontend.service"]="Odimrepo"
    ["tokpoint-backend.service"]="Tokpoint"
    ["tokpoint-frontend.service"]="Tokpoint"
    ["tokpoint-worker.service"]="Tokpoint"
    ["tokpoint-beat.service"]="Tokpoint"
)
# Note: tokpoint-docker.service is intentionally excluded — dockerwatch handles it.

echo ""
echo "══════════════════════════════════════════════════════"
echo "  systemd Drop-in Generator"
echo "══════════════════════════════════════════════════════"
echo "  Scan dir : $SYSTEMD_DIR"
echo "  Output   : $OUTPUT_DIR"
echo "  Mode     : $(if $DRY_RUN; then echo 'DRY RUN  (pass --apply to write files)'; else echo 'APPLY'; fi)"
echo "══════════════════════════════════════════════════════"
echo ""

if [ ! -d "$SYSTEMD_DIR" ]; then
    echo "ERROR: Directory not found: $SYSTEMD_DIR"
    echo "  Set SYSTEMD_DIR env var to point to your systemd unit directory."
    exit 1
fi

INSTALL_CMDS=()
FOUND=0
SKIPPED=0

for unit in "${!UNIT_MAP[@]}"; do
    canonical="${UNIT_MAP[$unit]}"
    unit_file="$SYSTEMD_DIR/$unit"

    if [ ! -f "$unit_file" ]; then
        echo "  ○ SKIP  $unit  (not found in $SYSTEMD_DIR)"
        SKIPPED=$((SKIPPED+1))
        continue
    fi

    echo "  ✓ FOUND  $unit  →  $canonical"
    FOUND=$((FOUND+1))

    dropin_content="[Service]
# Webhook notification drop-in for $unit
# Generated by deploy/generate-dropins.sh
ExecStartPost=/usr/local/bin/service-notify.sh up %n
ExecStopPost=/usr/local/bin/service-notify.sh down %n
OnFailure=notify@%n.service
"

    if ! $DRY_RUN; then
        dropin_dir="$OUTPUT_DIR/${unit}.d"
        mkdir -p "$dropin_dir"
        printf '%s' "$dropin_content" > "$dropin_dir/notify.conf"
        echo "       → Written: $dropin_dir/notify.conf"
    fi

    INSTALL_CMDS+=("sudo mkdir -p /etc/systemd/system/${unit}.d")
    INSTALL_CMDS+=("sudo cp $OUTPUT_DIR/${unit}.d/notify.conf /etc/systemd/system/${unit}.d/notify.conf")
done

echo ""
echo "──────────────────────────────────────────────────────"
echo "  Found: $FOUND units | Skipped: $SKIPPED units"
echo "──────────────────────────────────────────────────────"

if [ $FOUND -eq 0 ]; then
    echo ""
    echo "  No matching units found. Check SYSTEMD_DIR path."
    exit 0
fi

echo ""
echo "  Step 1 — Install notification script (if not done already):"
echo ""
echo "    sudo cp $SCRIPT_DIR/service-notify.sh /usr/local/bin/service-notify.sh"
echo "    sudo chmod +x /usr/local/bin/service-notify.sh"
echo "    sudo cp $SCRIPT_DIR/notify@.service /etc/systemd/system/notify@.service"
echo ""
echo "  Step 2 — Create /etc/default/service-notify with credentials:"
echo ""
echo "    sudo tee /etc/default/service-notify > /dev/null <<'EOF'"
echo "    WEBHOOK_URL=http://127.0.0.1:8080/api/v1/webhook"
echo "    HOOK_TOKEN=your-secret"
echo "    EOF"
echo ""

if ! $DRY_RUN; then
    echo "  Step 3 — Install generated drop-ins:"
    echo ""
    for cmd in "${INSTALL_CMDS[@]}"; do
        echo "    $cmd"
    done
    echo ""
    echo "  Step 4 — Reload systemd:"
    echo ""
    echo "    sudo systemctl daemon-reload"
    echo ""
    echo "  Done! Services will send webhooks on next start/stop."
else
    echo "  Step 3 — Run with --apply then install the generated files:"
    echo ""
    echo "    bash deploy/generate-dropins.sh --apply"
    for cmd in "${INSTALL_CMDS[@]}"; do
        echo "    $cmd"
    done
    echo "    sudo systemctl daemon-reload"
fi

echo ""
echo "══════════════════════════════════════════════════════"
